apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-v1
  namespace: canary-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pricing
      version: v1
  template:
    metadata:
      labels:
        app: pricing
        version: v1
    spec:
      containers:
        - name: app
          image: price-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
