apiVersion: v1
kind: Service
metadata:
  name: pricing
  namespace: canary-demo
  labels:
    app: pricing
spec:
  selector:
    app: pricing
  ports:
    - name: http
      port: 80
      targetPort: 8000
